package by.clever.servlet.dao.impl;

import by.clever.servlet.dao.MusicBandDAO;
import by.clever.servlet.dao.exception.DAOException;
import by.clever.servlet.entity.MusicBand;
import by.clever.servlet.entity.constant.MusicGenre;
import by.clever.servlet.dao.connectionpool.ConnectionPool;
import by.clever.servlet.dao.connectionpool.ConnectionPoolException;
import by.clever.servlet.dao.constant.DBMusicBandColumnName;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;


/**
 * Implementation of MusicBandDAO
 */
public class MusicBandDAOImpl implements MusicBandDAO {

    private final static int DEFAULT_PAGE_SIZE = 20;

    private final static String INSERT_NEW_BAND_SQL = "INSERT INTO music_band " +
            "(mb_name,mb_genre,mb_creationdate,mb_phonenumber,mb_email) VALUES (?,?,?,?,?) RETURNING mb_id";

    /**
     * @param band MusicBand object that need to be saved
     * @return UUID of saved object generated by DB
     */
    @Override
    public UUID save(MusicBand band) {

        UUID id;

        try (Connection connection = ConnectionPool.getInstance().takeConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(INSERT_NEW_BAND_SQL)) {

            preparedStatement.setString(1, band.getName());
            preparedStatement.setString(2, band.getGenre().toString());
            preparedStatement.setDate(3, Date.valueOf(band.getCreationDate()));
            preparedStatement.setString(4, band.getWorkPhoneNumber());
            preparedStatement.setString(5, band.getWorkEmail());

            boolean insertionResult = preparedStatement.execute();

            if (!insertionResult) {
                throw new DAOException("Save music band failed");
            }

            ResultSet resultSet = preparedStatement.getResultSet();

            if (resultSet.next()) {
                id = UUID.fromString(resultSet.getString(1));
            } else {
                throw new DAOException("Generation UUID failed");
            }

            return id;

        } catch (SQLException | ConnectionPoolException e) {
            throw new DAOException(e);
        }
    }

    private final static String SELECT_BAND_SQL = "SELECT " +
            "mb_id,mb_name,mb_genre,mb_creationdate,mb_phonenumber,mb_email " +
            "FROM music_band WHERE mb_id=? AND mb_isdeleted=false";

    /**
     * @param id ID of MusicBand object that requested
     * @return Requested optional value of MusicBand object
     */
    @Override
    public Optional<MusicBand> readByID(UUID id) {

        Optional<MusicBand> band;

        try (Connection connection = ConnectionPool.getInstance().takeConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(SELECT_BAND_SQL)) {

            preparedStatement.setObject(1, id);
            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                band = setMusicBand(resultSet);
            } else {
                throw new DAOException("Music band not found");
            }

            return band;

        } catch (SQLException | ConnectionPoolException e) {
            throw new DAOException(e);
        }
    }

    private final static String READ_ALL_BANDS_SQL = "SELECT * from music_band";

    @Override
    public List<MusicBand> readAll(int pageSize, int pageNumber) {

        if (pageSize == 0) {
            pageSize = DEFAULT_PAGE_SIZE;
        }

        List<MusicBand> musicBands = new ArrayList<>();

        try (Connection connection = ConnectionPool.getInstance().takeConnection();
             Statement statement = connection.createStatement()) {

            ResultSet result = statement.executeQuery(READ_ALL_BANDS_SQL);

            while (result.next()) {
                MusicBand musicBand = setMusicBand(result).orElseThrow();
                musicBands.add(musicBand);
            }

            return musicBands.stream()
                    .skip(pageNumber * pageSize)
                    .limit(pageNumber * pageSize + pageSize)
                    .toList();

        } catch (SQLException | ConnectionPoolException e) {
            throw new DAOException(e);
        }
    }

    private final static String UPDATE_BAND_SQL = "UPDATE music_band SET" +
            " mb_name=?,mb_genre=?,mb_creationdate=?,mb_phonenumber=?,mb_email=? " +
            "WHERE mb_id=?";

    /**
     * @param band MusicBand object that need to be updated
     * @return UUID of updated object
     */
    @Override
    public UUID update(MusicBand band) {

        UUID id;

        try (Connection connection = ConnectionPool.getInstance().takeConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(UPDATE_BAND_SQL)) {

            preparedStatement.setString(1, band.getName());
            preparedStatement.setString(2, band.getGenre().toString());
            preparedStatement.setDate(3, Date.valueOf(band.getCreationDate()));
            preparedStatement.setString(4, band.getWorkPhoneNumber());
            preparedStatement.setString(5, band.getWorkEmail());
            preparedStatement.setObject(6, band.getId());

            int insertionResult = preparedStatement.executeUpdate();

            if (insertionResult == 0) {
                throw new DAOException("Update music band failed");
            }

            return band.getId();

        } catch (SQLException | ConnectionPoolException e) {
            throw new DAOException(e);
        }
    }

    private final static String DELETE_BAND_SQL = "UPDATE music_band SET mb_isdeleted=true WHERE mb_id=?";

    /**
     * @param id Id og object that need to be deleted
     */
    @Override
    public void delete(UUID id) {

        try (Connection connection = ConnectionPool.getInstance().takeConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(DELETE_BAND_SQL)) {

            preparedStatement.setObject(1, id);
            int deletionResult = preparedStatement.executeUpdate();

            if (deletionResult == 0) {
                throw new DAOException("Deletion music band failed");
            }

        } catch (SQLException | ConnectionPoolException e) {
            throw new DAOException(e);
        }
    }

    private Optional<MusicBand> setMusicBand(ResultSet resultSet) throws SQLException {

        MusicBand band = new MusicBand();
        band.setId(UUID.fromString(resultSet.getString(DBMusicBandColumnName.ID_COLUMN)));
        band.setName(resultSet.getString(DBMusicBandColumnName.NAME_COLUMN));
        band.setGenre(MusicGenre.valueOf(resultSet.getString(DBMusicBandColumnName.GENRE_COLUMN)));
        band.setCreationDate(resultSet.getDate(DBMusicBandColumnName.CREATION_DATE_COLUMN).toLocalDate());
        band.setWorkPhoneNumber(resultSet.getString(DBMusicBandColumnName.PHONE_NUMBER_COLUMN));
        band.setWorkEmail(resultSet.getString(DBMusicBandColumnName.EMAIL_COLUMN));

        return Optional.of(band);
    }
}
